/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedCompaniesIndexRouteImport } from './routes/_authenticated/companies.index'
import { Route as AuthenticatedCompaniesCompanyIdRouteImport } from './routes/_authenticated/companies.$companyId'
import { Route as AuthenticatedCompaniesCompanyIdIndexRouteImport } from './routes/_authenticated/companies.$companyId.index'
import { Route as AuthenticatedCompaniesCompanyIdUsersRouteImport } from './routes/_authenticated/companies.$companyId.users'
import { Route as AuthenticatedCompaniesCompanyIdDriversRouteImport } from './routes/_authenticated/companies.$companyId.drivers'
import { Route as AuthenticatedCompaniesCompanyIdCarsRouteImport } from './routes/_authenticated/companies.$companyId.cars'
import { Route as AuthenticatedCompaniesCompanyIdAuditLogsRouteImport } from './routes/_authenticated/companies.$companyId.audit-logs'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesIndexRoute =
  AuthenticatedCompaniesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCompaniesRoute,
  } as any)
const AuthenticatedCompaniesCompanyIdRoute =
  AuthenticatedCompaniesCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => AuthenticatedCompaniesRoute,
  } as any)
const AuthenticatedCompaniesCompanyIdIndexRoute =
  AuthenticatedCompaniesCompanyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCompaniesCompanyIdRoute,
  } as any)
const AuthenticatedCompaniesCompanyIdUsersRoute =
  AuthenticatedCompaniesCompanyIdUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedCompaniesCompanyIdRoute,
  } as any)
const AuthenticatedCompaniesCompanyIdDriversRoute =
  AuthenticatedCompaniesCompanyIdDriversRouteImport.update({
    id: '/drivers',
    path: '/drivers',
    getParentRoute: () => AuthenticatedCompaniesCompanyIdRoute,
  } as any)
const AuthenticatedCompaniesCompanyIdCarsRoute =
  AuthenticatedCompaniesCompanyIdCarsRouteImport.update({
    id: '/cars',
    path: '/cars',
    getParentRoute: () => AuthenticatedCompaniesCompanyIdRoute,
  } as any)
const AuthenticatedCompaniesCompanyIdAuditLogsRoute =
  AuthenticatedCompaniesCompanyIdAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => AuthenticatedCompaniesCompanyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdRouteWithChildren
  '/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/companies/$companyId/audit-logs': typeof AuthenticatedCompaniesCompanyIdAuditLogsRoute
  '/companies/$companyId/cars': typeof AuthenticatedCompaniesCompanyIdCarsRoute
  '/companies/$companyId/drivers': typeof AuthenticatedCompaniesCompanyIdDriversRoute
  '/companies/$companyId/users': typeof AuthenticatedCompaniesCompanyIdUsersRoute
  '/companies/$companyId/': typeof AuthenticatedCompaniesCompanyIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/companies/$companyId/audit-logs': typeof AuthenticatedCompaniesCompanyIdAuditLogsRoute
  '/companies/$companyId/cars': typeof AuthenticatedCompaniesCompanyIdCarsRoute
  '/companies/$companyId/drivers': typeof AuthenticatedCompaniesCompanyIdDriversRoute
  '/companies/$companyId/users': typeof AuthenticatedCompaniesCompanyIdUsersRoute
  '/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdRouteWithChildren
  '/_authenticated/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/_authenticated/companies/$companyId/audit-logs': typeof AuthenticatedCompaniesCompanyIdAuditLogsRoute
  '/_authenticated/companies/$companyId/cars': typeof AuthenticatedCompaniesCompanyIdCarsRoute
  '/_authenticated/companies/$companyId/drivers': typeof AuthenticatedCompaniesCompanyIdDriversRoute
  '/_authenticated/companies/$companyId/users': typeof AuthenticatedCompaniesCompanyIdUsersRoute
  '/_authenticated/companies/$companyId/': typeof AuthenticatedCompaniesCompanyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/companies'
    | '/companies/$companyId'
    | '/companies/'
    | '/companies/$companyId/audit-logs'
    | '/companies/$companyId/cars'
    | '/companies/$companyId/drivers'
    | '/companies/$companyId/users'
    | '/companies/$companyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/companies'
    | '/companies/$companyId/audit-logs'
    | '/companies/$companyId/cars'
    | '/companies/$companyId/drivers'
    | '/companies/$companyId/users'
    | '/companies/$companyId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/companies'
    | '/_authenticated/'
    | '/_authenticated/companies/$companyId'
    | '/_authenticated/companies/'
    | '/_authenticated/companies/$companyId/audit-logs'
    | '/_authenticated/companies/$companyId/cars'
    | '/_authenticated/companies/$companyId/drivers'
    | '/_authenticated/companies/$companyId/users'
    | '/_authenticated/companies/$companyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies/': {
      id: '/_authenticated/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthenticatedCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedCompaniesRoute
    }
    '/_authenticated/companies/$companyId': {
      id: '/_authenticated/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedCompaniesRoute
    }
    '/_authenticated/companies/$companyId/': {
      id: '/_authenticated/companies/$companyId/'
      path: '/'
      fullPath: '/companies/$companyId/'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdIndexRouteImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdRoute
    }
    '/_authenticated/companies/$companyId/users': {
      id: '/_authenticated/companies/$companyId/users'
      path: '/users'
      fullPath: '/companies/$companyId/users'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdUsersRouteImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdRoute
    }
    '/_authenticated/companies/$companyId/drivers': {
      id: '/_authenticated/companies/$companyId/drivers'
      path: '/drivers'
      fullPath: '/companies/$companyId/drivers'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdDriversRouteImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdRoute
    }
    '/_authenticated/companies/$companyId/cars': {
      id: '/_authenticated/companies/$companyId/cars'
      path: '/cars'
      fullPath: '/companies/$companyId/cars'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdCarsRouteImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdRoute
    }
    '/_authenticated/companies/$companyId/audit-logs': {
      id: '/_authenticated/companies/$companyId/audit-logs'
      path: '/audit-logs'
      fullPath: '/companies/$companyId/audit-logs'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdAuditLogsRouteImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdRoute
    }
  }
}

interface AuthenticatedCompaniesCompanyIdRouteChildren {
  AuthenticatedCompaniesCompanyIdAuditLogsRoute: typeof AuthenticatedCompaniesCompanyIdAuditLogsRoute
  AuthenticatedCompaniesCompanyIdCarsRoute: typeof AuthenticatedCompaniesCompanyIdCarsRoute
  AuthenticatedCompaniesCompanyIdDriversRoute: typeof AuthenticatedCompaniesCompanyIdDriversRoute
  AuthenticatedCompaniesCompanyIdUsersRoute: typeof AuthenticatedCompaniesCompanyIdUsersRoute
  AuthenticatedCompaniesCompanyIdIndexRoute: typeof AuthenticatedCompaniesCompanyIdIndexRoute
}

const AuthenticatedCompaniesCompanyIdRouteChildren: AuthenticatedCompaniesCompanyIdRouteChildren =
  {
    AuthenticatedCompaniesCompanyIdAuditLogsRoute:
      AuthenticatedCompaniesCompanyIdAuditLogsRoute,
    AuthenticatedCompaniesCompanyIdCarsRoute:
      AuthenticatedCompaniesCompanyIdCarsRoute,
    AuthenticatedCompaniesCompanyIdDriversRoute:
      AuthenticatedCompaniesCompanyIdDriversRoute,
    AuthenticatedCompaniesCompanyIdUsersRoute:
      AuthenticatedCompaniesCompanyIdUsersRoute,
    AuthenticatedCompaniesCompanyIdIndexRoute:
      AuthenticatedCompaniesCompanyIdIndexRoute,
  }

const AuthenticatedCompaniesCompanyIdRouteWithChildren =
  AuthenticatedCompaniesCompanyIdRoute._addFileChildren(
    AuthenticatedCompaniesCompanyIdRouteChildren,
  )

interface AuthenticatedCompaniesRouteChildren {
  AuthenticatedCompaniesCompanyIdRoute: typeof AuthenticatedCompaniesCompanyIdRouteWithChildren
  AuthenticatedCompaniesIndexRoute: typeof AuthenticatedCompaniesIndexRoute
}

const AuthenticatedCompaniesRouteChildren: AuthenticatedCompaniesRouteChildren =
  {
    AuthenticatedCompaniesCompanyIdRoute:
      AuthenticatedCompaniesCompanyIdRouteWithChildren,
    AuthenticatedCompaniesIndexRoute: AuthenticatedCompaniesIndexRoute,
  }

const AuthenticatedCompaniesRouteWithChildren =
  AuthenticatedCompaniesRoute._addFileChildren(
    AuthenticatedCompaniesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
