packages:
  - "apps/*"
  - "packages/*"

catalog:
  zod: ^4.4.3
  '@tanstack/react-query': ^5.90.12
  leaflet: ^1.9.4
  react-leaflet: ^5.0.0

allowBuilds:
  '@scarf/scarf': false
  esbuild: false
  unrs-resolver: true
