/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedDriversRouteImport } from './routes/_authenticated/drivers'
import { Route as AuthenticatedCarsRouteImport } from './routes/_authenticated/cars'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedCarsIndexRouteImport } from './routes/_authenticated/cars.index'
import { Route as AuthenticatedCarsCarIdRouteImport } from './routes/_authenticated/cars.$carId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriversRoute = AuthenticatedDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCarsRoute = AuthenticatedCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCarsIndexRoute = AuthenticatedCarsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCarsRoute,
} as any)
const AuthenticatedCarsCarIdRoute = AuthenticatedCarsCarIdRouteImport.update({
  id: '/$carId',
  path: '/$carId',
  getParentRoute: () => AuthenticatedCarsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/cars': typeof AuthenticatedCarsRouteWithChildren
  '/drivers': typeof AuthenticatedDriversRoute
  '/map': typeof AuthenticatedMapRoute
  '/users': typeof AuthenticatedUsersRoute
  '/cars/$carId': typeof AuthenticatedCarsCarIdRoute
  '/cars/': typeof AuthenticatedCarsIndexRoute
}
export interface FileRoutesByTo {
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/drivers': typeof AuthenticatedDriversRoute
  '/map': typeof AuthenticatedMapRoute
  '/users': typeof AuthenticatedUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/cars/$carId': typeof AuthenticatedCarsCarIdRoute
  '/cars': typeof AuthenticatedCarsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/cars': typeof AuthenticatedCarsRouteWithChildren
  '/_authenticated/drivers': typeof AuthenticatedDriversRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/cars/$carId': typeof AuthenticatedCarsCarIdRoute
  '/_authenticated/cars/': typeof AuthenticatedCarsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/audit-logs'
    | '/cars'
    | '/drivers'
    | '/map'
    | '/users'
    | '/cars/$carId'
    | '/cars/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/change-password'
    | '/login'
    | '/audit-logs'
    | '/drivers'
    | '/map'
    | '/users'
    | '/'
    | '/cars/$carId'
    | '/cars'
  id:
    | '__root__'
    | '/_authenticated'
    | '/change-password'
    | '/login'
    | '/_authenticated/audit-logs'
    | '/_authenticated/cars'
    | '/_authenticated/drivers'
    | '/_authenticated/map'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/cars/$carId'
    | '/_authenticated/cars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drivers': {
      id: '/_authenticated/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthenticatedDriversRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cars': {
      id: '/_authenticated/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof AuthenticatedCarsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cars/': {
      id: '/_authenticated/cars/'
      path: '/'
      fullPath: '/cars/'
      preLoaderRoute: typeof AuthenticatedCarsIndexRouteImport
      parentRoute: typeof AuthenticatedCarsRoute
    }
    '/_authenticated/cars/$carId': {
      id: '/_authenticated/cars/$carId'
      path: '/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof AuthenticatedCarsCarIdRouteImport
      parentRoute: typeof AuthenticatedCarsRoute
    }
  }
}

interface AuthenticatedCarsRouteChildren {
  AuthenticatedCarsCarIdRoute: typeof AuthenticatedCarsCarIdRoute
  AuthenticatedCarsIndexRoute: typeof AuthenticatedCarsIndexRoute
}

const AuthenticatedCarsRouteChildren: AuthenticatedCarsRouteChildren = {
  AuthenticatedCarsCarIdRoute: AuthenticatedCarsCarIdRoute,
  AuthenticatedCarsIndexRoute: AuthenticatedCarsIndexRoute,
}

const AuthenticatedCarsRouteWithChildren =
  AuthenticatedCarsRoute._addFileChildren(AuthenticatedCarsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedCarsRoute: typeof AuthenticatedCarsRouteWithChildren
  AuthenticatedDriversRoute: typeof AuthenticatedDriversRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedCarsRoute: AuthenticatedCarsRouteWithChildren,
  AuthenticatedDriversRoute: AuthenticatedDriversRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
