export const COMPANY_NAME_MAX_LENGTH = 200;
export const COMPANY_NATIONAL_ID_MAX_LENGTH = 32;
export const COMPANY_PHONE_MAX_LENGTH = 20;
export const COMPANY_ADDRESS_MAX_LENGTH = 500;
export const COMPANY_NOTE_MAX_LENGTH = 5000;
