// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fa'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * S​w​i​t​c​h​ ​t​o​ ​l​i​g​h​t​ ​m​o​d​e
		 */
		switchToLightMode: string
		/**
		 * S​w​i​t​c​h​ ​t​o​ ​d​a​r​k​ ​m​o​d​e
		 */
		switchToDarkMode: string
		/**
		 * S​w​i​t​c​h​ ​t​o​ ​E​n​g​l​i​s​h
		 */
		switchToEnglish: string
		/**
		 * S​w​i​t​c​h​ ​t​o​ ​P​e​r​s​i​a​n
		 */
		switchToPersian: string
		/**
		 * E​N
		 */
		languageEn: string
		/**
		 * F​A
		 */
		languageFa: string
	}
	validation: {
		/**
		 * U​s​e​r​n​a​m​e​ ​i​s​ ​r​e​q​u​i​r​e​d
		 */
		usernameRequired: string
		/**
		 * U​s​e​r​n​a​m​e​ ​m​u​s​t​ ​b​e​ ​3​–​3​2​ ​c​h​a​r​a​c​t​e​r​s​ ​a​n​d​ ​c​o​n​t​a​i​n​ ​o​n​l​y​ ​l​e​t​t​e​r​s​,​ ​n​u​m​b​e​r​s​,​ ​u​n​d​e​r​s​c​o​r​e​s​,​ ​a​n​d​ ​h​y​p​h​e​n​s
		 */
		usernameInvalid: string
		/**
		 * P​a​s​s​w​o​r​d​ ​i​s​ ​r​e​q​u​i​r​e​d
		 */
		passwordRequired: string
		/**
		 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​{​m​i​n​}​ ​c​h​a​r​a​c​t​e​r​s
		 * @param {number} min
		 */
		passwordMinLength: RequiredParams<'min'>
		/**
		 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​u​p​p​e​r​c​a​s​e​ ​l​e​t​t​e​r
		 */
		passwordUppercase: string
		/**
		 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​l​o​w​e​r​c​a​s​e​ ​l​e​t​t​e​r
		 */
		passwordLowercase: string
		/**
		 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​n​u​m​b​e​r
		 */
		passwordDigit: string
		/**
		 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r
		 */
		passwordSpecial: string
		/**
		 * C​o​m​p​a​n​y​ ​n​a​m​e​ ​i​s​ ​r​e​q​u​i​r​e​d
		 */
		companyNameRequired: string
		/**
		 * C​o​m​p​a​n​y​ ​n​a​m​e​ ​m​u​s​t​ ​b​e​ ​a​t​ ​m​o​s​t​ ​{​m​a​x​}​ ​c​h​a​r​a​c​t​e​r​s
		 * @param {number} max
		 */
		companyNameTooLong: RequiredParams<'max'>
		/**
		 * N​a​t​i​o​n​a​l​ ​I​D​ ​i​s​ ​r​e​q​u​i​r​e​d
		 */
		companyNationalIdRequired: string
		/**
		 * N​a​t​i​o​n​a​l​ ​I​D​ ​m​u​s​t​ ​b​e​ ​a​t​ ​m​o​s​t​ ​{​m​a​x​}​ ​c​h​a​r​a​c​t​e​r​s
		 * @param {number} max
		 */
		companyNationalIdTooLong: RequiredParams<'max'>
		/**
		 * P​h​o​n​e​ ​n​u​m​b​e​r​ ​i​s​ ​r​e​q​u​i​r​e​d
		 */
		companyPhoneNumberRequired: string
		/**
		 * P​h​o​n​e​ ​n​u​m​b​e​r​ ​m​u​s​t​ ​b​e​ ​a​t​ ​m​o​s​t​ ​{​m​a​x​}​ ​c​h​a​r​a​c​t​e​r​s
		 * @param {number} max
		 */
		companyPhoneNumberTooLong: RequiredParams<'max'>
		/**
		 * A​d​d​r​e​s​s​ ​m​u​s​t​ ​b​e​ ​a​t​ ​m​o​s​t​ ​{​m​a​x​}​ ​c​h​a​r​a​c​t​e​r​s
		 * @param {number} max
		 */
		companyAddressTooLong: RequiredParams<'max'>
		/**
		 * N​o​t​e​ ​m​u​s​t​ ​b​e​ ​a​t​ ​m​o​s​t​ ​{​m​a​x​}​ ​c​h​a​r​a​c​t​e​r​s
		 * @param {number} max
		 */
		companyNoteTooLong: RequiredParams<'max'>
	}
	internalPanel: {
		login: {
			/**
			 * I​n​t​e​r​n​a​l​ ​P​a​n​e​l
			 */
			title: string
			/**
			 * A​u​t​h​o​r​i​z​e​d​ ​a​c​c​e​s​s​ ​o​n​l​y
			 */
			subtitle: string
			/**
			 * U​s​e​r​n​a​m​e
			 */
			username: string
			/**
			 * P​a​s​s​w​o​r​d
			 */
			password: string
			/**
			 * y​o​u​r​_​u​s​e​r​n​a​m​e
			 */
			usernamePlaceholder: string
			/**
			 * I​n​v​a​l​i​d​ ​u​s​e​r​n​a​m​e​ ​o​r​ ​p​a​s​s​w​o​r​d​.
			 */
			invalidCredentials: string
			/**
			 * S​i​g​n​i​n​g​ ​i​n
			 */
			signingIn: string
			/**
			 * S​i​g​n​ ​i​n
			 */
			signIn: string
		}
		home: {
			/**
			 * D​a​s​h​b​o​a​r​d
			 */
			title: string
			/**
			 * W​e​l​c​o​m​e​ ​b​a​c​k​,​ ​{​f​i​r​s​t​N​a​m​e​}
			 * @param {string} firstName
			 */
			welcome: RequiredParams<'firstName'>
			/**
			 * S​i​g​n​e​d​ ​i​n​ ​a​s​ ​{​f​i​r​s​t​N​a​m​e​}​ ​{​l​a​s​t​N​a​m​e​}​ ​(​{​u​s​e​r​n​a​m​e​}​)
			 * @param {string} firstName
			 * @param {string} lastName
			 * @param {string} username
			 */
			signedInAs: RequiredParams<'firstName' | 'lastName' | 'username'>
			/**
			 * S​i​g​n​i​n​g​ ​o​u​t​…
			 */
			signingOut: string
			/**
			 * S​i​g​n​ ​o​u​t
			 */
			signOut: string
		}
		nav: {
			/**
			 * D​a​s​h​b​o​a​r​d
			 */
			dashboard: string
			/**
			 * C​o​m​p​a​n​i​e​s
			 */
			companies: string
			/**
			 * O​p​e​n​ ​m​e​n​u
			 */
			openMenu: string
			/**
			 * S​i​g​n​ ​o​u​t
			 */
			signOut: string
			/**
			 * S​i​g​n​i​n​g​ ​o​u​t​…
			 */
			signingOut: string
			/**
			 * S​i​g​n​ ​o​u​t​?
			 */
			signOutConfirmTitle: string
			/**
			 * Y​o​u​ ​w​i​l​l​ ​n​e​e​d​ ​t​o​ ​s​i​g​n​ ​i​n​ ​a​g​a​i​n​ ​t​o​ ​a​c​c​e​s​s​ ​t​h​e​ ​i​n​t​e​r​n​a​l​ ​p​a​n​e​l​.
			 */
			signOutConfirmDescription: string
			/**
			 * S​i​g​n​ ​o​u​t
			 */
			signOutConfirm: string
			/**
			 * C​a​n​c​e​l
			 */
			cancel: string
		}
		shell: {
			/**
			 * F​u​e​l​ ​C​a​r​r​i​e​r
			 */
			brand: string
			/**
			 * I​n​t​e​r​n​a​l
			 */
			brandSubtitle: string
		}
		companies: {
			/**
			 * C​o​m​p​a​n​i​e​s
			 */
			title: string
			/**
			 * C​r​e​a​t​e​ ​a​n​d​ ​m​a​n​a​g​e​ ​c​a​r​r​i​e​r​ ​c​o​m​p​a​n​i​e​s
			 */
			subtitle: string
			/**
			 * N​a​m​e
			 */
			name: string
			/**
			 * N​a​t​i​o​n​a​l​ ​I​D
			 */
			nationalId: string
			/**
			 * P​h​o​n​e​ ​n​u​m​b​e​r
			 */
			phoneNumber: string
			/**
			 * A​d​d​r​e​s​s
			 */
			address: string
			/**
			 * N​o​t​e
			 */
			note: string
			/**
			 * A​c​m​e​ ​L​o​g​i​s​t​i​c​s
			 */
			namePlaceholder: string
			/**
			 * 1​2​3​4​5​6​7​8​9​0​1
			 */
			nationalIdPlaceholder: string
			/**
			 * +​9​8​ ​2​1​ ​1​2​3​4​ ​5​6​7​8
			 */
			phoneNumberPlaceholder: string
			/**
			 * 1​2​3​ ​M​a​i​n​ ​S​t​,​ ​T​e​h​r​a​n
			 */
			addressPlaceholder: string
			/**
			 * A​d​d​i​t​i​o​n​a​l​ ​n​o​t​e​s​ ​a​b​o​u​t​ ​t​h​i​s​ ​c​o​m​p​a​n​y
			 */
			notePlaceholder: string
			/**
			 * A​d​d​ ​c​o​m​p​a​n​y
			 */
			create: string
			/**
			 * A​d​d​i​n​g​…
			 */
			creating: string
			/**
			 * C​o​u​l​d​ ​n​o​t​ ​c​r​e​a​t​e​ ​c​o​m​p​a​n​y​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
			 */
			createFailed: string
			/**
			 * S​a​v​e​ ​c​h​a​n​g​e​s
			 */
			update: string
			/**
			 * S​a​v​i​n​g​…
			 */
			updating: string
			/**
			 * C​o​u​l​d​ ​n​o​t​ ​u​p​d​a​t​e​ ​c​o​m​p​a​n​y​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
			 */
			updateFailed: string
			/**
			 * E​d​i​t
			 */
			edit: string
			/**
			 * V​i​e​w
			 */
			view: string
			/**
			 * D​e​l​e​t​e
			 */
			'delete': string
			/**
			 * O​p​e​r​a​t​i​o​n​s
			 */
			operations: string
			/**
			 * A​d​d​ ​c​o​m​p​a​n​y
			 */
			createTitle: string
			/**
			 * E​d​i​t​ ​c​o​m​p​a​n​y
			 */
			editTitle: string
			/**
			 * D​e​l​e​t​e​ ​c​o​m​p​a​n​y​?
			 */
			deleteConfirmTitle: string
			/**
			 * T​h​i​s​ ​w​i​l​l​ ​p​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​ ​{​n​a​m​e​}​.​ ​T​h​i​s​ ​a​c​t​i​o​n​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
			 * @param {string} name
			 */
			deleteConfirmDescription: RequiredParams<'name'>
			/**
			 * D​e​l​e​t​e
			 */
			deleteConfirm: string
			/**
			 * D​e​l​e​t​i​n​g​…
			 */
			deleting: string
			/**
			 * C​o​u​l​d​ ​n​o​t​ ​d​e​l​e​t​e​ ​c​o​m​p​a​n​y​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
			 */
			deleteFailed: string
			/**
			 * L​o​a​d​i​n​g​…
			 */
			loading: string
			/**
			 * N​o​ ​c​o​m​p​a​n​i​e​s​ ​y​e​t​.​ ​A​d​d​ ​y​o​u​r​ ​f​i​r​s​t​ ​c​o​m​p​a​n​y​.
			 */
			empty: string
			/**
			 * A​ ​c​o​m​p​a​n​y​ ​w​i​t​h​ ​t​h​i​s​ ​n​a​t​i​o​n​a​l​ ​I​D​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​.
			 */
			duplicateNationalId: string
			/**
			 * —
			 */
			emptyCell: string
			/**
			 * B​a​c​k​ ​t​o​ ​c​o​m​p​a​n​i​e​s
			 */
			backToList: string
			/**
			 * C​o​m​p​a​n​y​ ​n​o​t​ ​f​o​u​n​d​.
			 */
			notFound: string
			/**
			 * T​h​i​s​ ​c​o​m​p​a​n​y​ ​m​a​y​ ​h​a​v​e​ ​b​e​e​n​ ​d​e​l​e​t​e​d​ ​o​r​ ​t​h​e​ ​l​i​n​k​ ​i​s​ ​i​n​v​a​l​i​d​.
			 */
			notFoundDescription: string
			detail: {
				/**
				 * C​o​m​p​a​n​y​ ​d​e​t​a​i​l​s
				 */
				overviewTitle: string
				/**
				 * C​o​m​p​a​n​y​ ​u​s​e​r​s
				 */
				usersTitle: string
				/**
				 * E​x​t​e​r​n​a​l​ ​p​a​n​e​l​ ​l​o​g​i​n​ ​a​c​c​o​u​n​t​s​ ​f​o​r​ ​t​h​i​s​ ​c​o​m​p​a​n​y
				 */
				usersSubtitle: string
				/**
				 * D​r​i​v​e​r​s
				 */
				driversTitle: string
				/**
				 * D​r​i​v​e​r​s​ ​a​s​s​i​g​n​e​d​ ​t​o​ ​t​h​i​s​ ​c​o​m​p​a​n​y
				 */
				driversSubtitle: string
				/**
				 * C​a​r​s
				 */
				carsTitle: string
				/**
				 * V​e​h​i​c​l​e​s​ ​r​e​g​i​s​t​e​r​e​d​ ​t​o​ ​t​h​i​s​ ​c​o​m​p​a​n​y
				 */
				carsSubtitle: string
				/**
				 * A​d​d​ ​u​s​e​r
				 */
				addUser: string
				/**
				 * A​d​d​ ​d​r​i​v​e​r
				 */
				addDriver: string
				/**
				 * A​d​d​ ​c​a​r
				 */
				addCar: string
				/**
				 * F​i​r​s​t​ ​n​a​m​e
				 */
				firstName: string
				/**
				 * L​a​s​t​ ​n​a​m​e
				 */
				lastName: string
				/**
				 * U​s​e​r​n​a​m​e
				 */
				username: string
				/**
				 * E​m​a​i​l
				 */
				email: string
				/**
				 * P​a​s​s​w​o​r​d
				 */
				password: string
				/**
				 * N​e​w​ ​p​a​s​s​w​o​r​d​ ​(​l​e​a​v​e​ ​b​l​a​n​k​ ​t​o​ ​k​e​e​p​ ​c​u​r​r​e​n​t​)
				 */
				passwordOptional: string
				/**
				 * L​i​c​e​n​s​e​ ​p​l​a​t​e
				 */
				licensePlate: string
				/**
				 * D​r​i​v​e​r
				 */
				driver: string
				/**
				 * C​a​r
				 */
				car: string
				/**
				 * N​o​ ​d​r​i​v​e​r​ ​a​s​s​i​g​n​e​d
				 */
				noDriver: string
				/**
				 * N​o​ ​c​a​r​ ​a​s​s​i​g​n​e​d
				 */
				noCar: string
				/**
				 * A​d​d​ ​c​o​m​p​a​n​y​ ​u​s​e​r
				 */
				userCreateTitle: string
				/**
				 * E​d​i​t​ ​c​o​m​p​a​n​y​ ​u​s​e​r
				 */
				userEditTitle: string
				/**
				 * A​d​d​ ​d​r​i​v​e​r
				 */
				driverCreateTitle: string
				/**
				 * E​d​i​t​ ​d​r​i​v​e​r
				 */
				driverEditTitle: string
				/**
				 * A​d​d​ ​c​a​r
				 */
				carCreateTitle: string
				/**
				 * E​d​i​t​ ​c​a​r
				 */
				carEditTitle: string
				/**
				 * N​o​ ​u​s​e​r​s​ ​y​e​t​ ​f​o​r​ ​t​h​i​s​ ​c​o​m​p​a​n​y​.
				 */
				usersEmpty: string
				/**
				 * N​o​ ​d​r​i​v​e​r​s​ ​y​e​t​ ​f​o​r​ ​t​h​i​s​ ​c​o​m​p​a​n​y​.
				 */
				driversEmpty: string
				/**
				 * N​o​ ​c​a​r​s​ ​y​e​t​ ​f​o​r​ ​t​h​i​s​ ​c​o​m​p​a​n​y​.
				 */
				carsEmpty: string
				/**
				 * D​e​l​e​t​e​ ​u​s​e​r​?
				 */
				deleteUserTitle: string
				/**
				 * T​h​i​s​ ​w​i​l​l​ ​p​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​ ​{​n​a​m​e​}​.​ ​T​h​e​y​ ​w​i​l​l​ ​n​o​ ​l​o​n​g​e​r​ ​b​e​ ​a​b​l​e​ ​t​o​ ​s​i​g​n​ ​i​n​.
				 * @param {string} name
				 */
				deleteUserDescription: RequiredParams<'name'>
				/**
				 * D​e​l​e​t​e​ ​d​r​i​v​e​r​?
				 */
				deleteDriverTitle: string
				/**
				 * T​h​i​s​ ​w​i​l​l​ ​p​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​ ​{​n​a​m​e​}​.​ ​T​h​i​s​ ​a​c​t​i​o​n​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
				 * @param {string} name
				 */
				deleteDriverDescription: RequiredParams<'name'>
				/**
				 * D​e​l​e​t​e​ ​c​a​r​?
				 */
				deleteCarTitle: string
				/**
				 * T​h​i​s​ ​w​i​l​l​ ​p​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​ ​{​l​i​c​e​n​s​e​P​l​a​t​e​}​.​ ​T​h​i​s​ ​a​c​t​i​o​n​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
				 * @param {string} licensePlate
				 */
				deleteCarDescription: RequiredParams<'licensePlate'>
				/**
				 * C​o​u​l​d​ ​n​o​t​ ​s​a​v​e​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
				 */
				createFailed: string
				/**
				 * C​o​u​l​d​ ​n​o​t​ ​d​e​l​e​t​e​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
				 */
				deleteFailed: string
				/**
				 * T​h​i​s​ ​u​s​e​r​n​a​m​e​ ​i​s​ ​a​l​r​e​a​d​y​ ​t​a​k​e​n​.
				 */
				duplicateUsername: string
				/**
				 * A​ ​u​s​e​r​ ​w​i​t​h​ ​t​h​i​s​ ​n​a​t​i​o​n​a​l​ ​I​D​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​.
				 */
				duplicateNationalId: string
				/**
				 * A​ ​d​r​i​v​e​r​ ​w​i​t​h​ ​t​h​i​s​ ​n​a​t​i​o​n​a​l​ ​I​D​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​.
				 */
				duplicateDriverNationalId: string
			}
		}
	}
	externalPanel: {
		home: {
			/**
			 * E​x​t​e​r​n​a​l​ ​P​a​n​e​l
			 */
			title: string
			/**
			 * T​a​n​S​t​a​c​k​ ​R​o​u​t​e​r​ ​a​n​d​ ​R​e​a​c​t​ ​Q​u​e​r​y​ ​a​r​e​ ​c​o​n​f​i​g​u​r​e​d​.
			 */
			description: string
		}
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * Switch to light mode
		 */
		switchToLightMode: () => LocalizedString
		/**
		 * Switch to dark mode
		 */
		switchToDarkMode: () => LocalizedString
		/**
		 * Switch to English
		 */
		switchToEnglish: () => LocalizedString
		/**
		 * Switch to Persian
		 */
		switchToPersian: () => LocalizedString
		/**
		 * EN
		 */
		languageEn: () => LocalizedString
		/**
		 * FA
		 */
		languageFa: () => LocalizedString
	}
	validation: {
		/**
		 * Username is required
		 */
		usernameRequired: () => LocalizedString
		/**
		 * Username must be 3–32 characters and contain only letters, numbers, underscores, and hyphens
		 */
		usernameInvalid: () => LocalizedString
		/**
		 * Password is required
		 */
		passwordRequired: () => LocalizedString
		/**
		 * Password must be at least {min} characters
		 */
		passwordMinLength: (arg: { min: number }) => LocalizedString
		/**
		 * Password must contain at least one uppercase letter
		 */
		passwordUppercase: () => LocalizedString
		/**
		 * Password must contain at least one lowercase letter
		 */
		passwordLowercase: () => LocalizedString
		/**
		 * Password must contain at least one number
		 */
		passwordDigit: () => LocalizedString
		/**
		 * Password must contain at least one special character
		 */
		passwordSpecial: () => LocalizedString
		/**
		 * Company name is required
		 */
		companyNameRequired: () => LocalizedString
		/**
		 * Company name must be at most {max} characters
		 */
		companyNameTooLong: (arg: { max: number }) => LocalizedString
		/**
		 * National ID is required
		 */
		companyNationalIdRequired: () => LocalizedString
		/**
		 * National ID must be at most {max} characters
		 */
		companyNationalIdTooLong: (arg: { max: number }) => LocalizedString
		/**
		 * Phone number is required
		 */
		companyPhoneNumberRequired: () => LocalizedString
		/**
		 * Phone number must be at most {max} characters
		 */
		companyPhoneNumberTooLong: (arg: { max: number }) => LocalizedString
		/**
		 * Address must be at most {max} characters
		 */
		companyAddressTooLong: (arg: { max: number }) => LocalizedString
		/**
		 * Note must be at most {max} characters
		 */
		companyNoteTooLong: (arg: { max: number }) => LocalizedString
	}
	internalPanel: {
		login: {
			/**
			 * Internal Panel
			 */
			title: () => LocalizedString
			/**
			 * Authorized access only
			 */
			subtitle: () => LocalizedString
			/**
			 * Username
			 */
			username: () => LocalizedString
			/**
			 * Password
			 */
			password: () => LocalizedString
			/**
			 * your_username
			 */
			usernamePlaceholder: () => LocalizedString
			/**
			 * Invalid username or password.
			 */
			invalidCredentials: () => LocalizedString
			/**
			 * Signing in
			 */
			signingIn: () => LocalizedString
			/**
			 * Sign in
			 */
			signIn: () => LocalizedString
		}
		home: {
			/**
			 * Dashboard
			 */
			title: () => LocalizedString
			/**
			 * Welcome back, {firstName}
			 */
			welcome: (arg: { firstName: string }) => LocalizedString
			/**
			 * Signed in as {firstName} {lastName} ({username})
			 */
			signedInAs: (arg: { firstName: string, lastName: string, username: string }) => LocalizedString
			/**
			 * Signing out…
			 */
			signingOut: () => LocalizedString
			/**
			 * Sign out
			 */
			signOut: () => LocalizedString
		}
		nav: {
			/**
			 * Dashboard
			 */
			dashboard: () => LocalizedString
			/**
			 * Companies
			 */
			companies: () => LocalizedString
			/**
			 * Open menu
			 */
			openMenu: () => LocalizedString
			/**
			 * Sign out
			 */
			signOut: () => LocalizedString
			/**
			 * Signing out…
			 */
			signingOut: () => LocalizedString
			/**
			 * Sign out?
			 */
			signOutConfirmTitle: () => LocalizedString
			/**
			 * You will need to sign in again to access the internal panel.
			 */
			signOutConfirmDescription: () => LocalizedString
			/**
			 * Sign out
			 */
			signOutConfirm: () => LocalizedString
			/**
			 * Cancel
			 */
			cancel: () => LocalizedString
		}
		shell: {
			/**
			 * Fuel Carrier
			 */
			brand: () => LocalizedString
			/**
			 * Internal
			 */
			brandSubtitle: () => LocalizedString
		}
		companies: {
			/**
			 * Companies
			 */
			title: () => LocalizedString
			/**
			 * Create and manage carrier companies
			 */
			subtitle: () => LocalizedString
			/**
			 * Name
			 */
			name: () => LocalizedString
			/**
			 * National ID
			 */
			nationalId: () => LocalizedString
			/**
			 * Phone number
			 */
			phoneNumber: () => LocalizedString
			/**
			 * Address
			 */
			address: () => LocalizedString
			/**
			 * Note
			 */
			note: () => LocalizedString
			/**
			 * Acme Logistics
			 */
			namePlaceholder: () => LocalizedString
			/**
			 * 12345678901
			 */
			nationalIdPlaceholder: () => LocalizedString
			/**
			 * +98 21 1234 5678
			 */
			phoneNumberPlaceholder: () => LocalizedString
			/**
			 * 123 Main St, Tehran
			 */
			addressPlaceholder: () => LocalizedString
			/**
			 * Additional notes about this company
			 */
			notePlaceholder: () => LocalizedString
			/**
			 * Add company
			 */
			create: () => LocalizedString
			/**
			 * Adding…
			 */
			creating: () => LocalizedString
			/**
			 * Could not create company. Please try again.
			 */
			createFailed: () => LocalizedString
			/**
			 * Save changes
			 */
			update: () => LocalizedString
			/**
			 * Saving…
			 */
			updating: () => LocalizedString
			/**
			 * Could not update company. Please try again.
			 */
			updateFailed: () => LocalizedString
			/**
			 * Edit
			 */
			edit: () => LocalizedString
			/**
			 * View
			 */
			view: () => LocalizedString
			/**
			 * Delete
			 */
			'delete': () => LocalizedString
			/**
			 * Operations
			 */
			operations: () => LocalizedString
			/**
			 * Add company
			 */
			createTitle: () => LocalizedString
			/**
			 * Edit company
			 */
			editTitle: () => LocalizedString
			/**
			 * Delete company?
			 */
			deleteConfirmTitle: () => LocalizedString
			/**
			 * This will permanently delete {name}. This action cannot be undone.
			 */
			deleteConfirmDescription: (arg: { name: string }) => LocalizedString
			/**
			 * Delete
			 */
			deleteConfirm: () => LocalizedString
			/**
			 * Deleting…
			 */
			deleting: () => LocalizedString
			/**
			 * Could not delete company. Please try again.
			 */
			deleteFailed: () => LocalizedString
			/**
			 * Loading…
			 */
			loading: () => LocalizedString
			/**
			 * No companies yet. Add your first company.
			 */
			empty: () => LocalizedString
			/**
			 * A company with this national ID already exists.
			 */
			duplicateNationalId: () => LocalizedString
			/**
			 * —
			 */
			emptyCell: () => LocalizedString
			/**
			 * Back to companies
			 */
			backToList: () => LocalizedString
			/**
			 * Company not found.
			 */
			notFound: () => LocalizedString
			/**
			 * This company may have been deleted or the link is invalid.
			 */
			notFoundDescription: () => LocalizedString
			detail: {
				/**
				 * Company details
				 */
				overviewTitle: () => LocalizedString
				/**
				 * Company users
				 */
				usersTitle: () => LocalizedString
				/**
				 * External panel login accounts for this company
				 */
				usersSubtitle: () => LocalizedString
				/**
				 * Drivers
				 */
				driversTitle: () => LocalizedString
				/**
				 * Drivers assigned to this company
				 */
				driversSubtitle: () => LocalizedString
				/**
				 * Cars
				 */
				carsTitle: () => LocalizedString
				/**
				 * Vehicles registered to this company
				 */
				carsSubtitle: () => LocalizedString
				/**
				 * Add user
				 */
				addUser: () => LocalizedString
				/**
				 * Add driver
				 */
				addDriver: () => LocalizedString
				/**
				 * Add car
				 */
				addCar: () => LocalizedString
				/**
				 * First name
				 */
				firstName: () => LocalizedString
				/**
				 * Last name
				 */
				lastName: () => LocalizedString
				/**
				 * Username
				 */
				username: () => LocalizedString
				/**
				 * Email
				 */
				email: () => LocalizedString
				/**
				 * Password
				 */
				password: () => LocalizedString
				/**
				 * New password (leave blank to keep current)
				 */
				passwordOptional: () => LocalizedString
				/**
				 * License plate
				 */
				licensePlate: () => LocalizedString
				/**
				 * Driver
				 */
				driver: () => LocalizedString
				/**
				 * Car
				 */
				car: () => LocalizedString
				/**
				 * No driver assigned
				 */
				noDriver: () => LocalizedString
				/**
				 * No car assigned
				 */
				noCar: () => LocalizedString
				/**
				 * Add company user
				 */
				userCreateTitle: () => LocalizedString
				/**
				 * Edit company user
				 */
				userEditTitle: () => LocalizedString
				/**
				 * Add driver
				 */
				driverCreateTitle: () => LocalizedString
				/**
				 * Edit driver
				 */
				driverEditTitle: () => LocalizedString
				/**
				 * Add car
				 */
				carCreateTitle: () => LocalizedString
				/**
				 * Edit car
				 */
				carEditTitle: () => LocalizedString
				/**
				 * No users yet for this company.
				 */
				usersEmpty: () => LocalizedString
				/**
				 * No drivers yet for this company.
				 */
				driversEmpty: () => LocalizedString
				/**
				 * No cars yet for this company.
				 */
				carsEmpty: () => LocalizedString
				/**
				 * Delete user?
				 */
				deleteUserTitle: () => LocalizedString
				/**
				 * This will permanently delete {name}. They will no longer be able to sign in.
				 */
				deleteUserDescription: (arg: { name: string }) => LocalizedString
				/**
				 * Delete driver?
				 */
				deleteDriverTitle: () => LocalizedString
				/**
				 * This will permanently delete {name}. This action cannot be undone.
				 */
				deleteDriverDescription: (arg: { name: string }) => LocalizedString
				/**
				 * Delete car?
				 */
				deleteCarTitle: () => LocalizedString
				/**
				 * This will permanently delete {licensePlate}. This action cannot be undone.
				 */
				deleteCarDescription: (arg: { licensePlate: string }) => LocalizedString
				/**
				 * Could not save. Please try again.
				 */
				createFailed: () => LocalizedString
				/**
				 * Could not delete. Please try again.
				 */
				deleteFailed: () => LocalizedString
				/**
				 * This username is already taken.
				 */
				duplicateUsername: () => LocalizedString
				/**
				 * A user with this national ID already exists.
				 */
				duplicateNationalId: () => LocalizedString
				/**
				 * A driver with this national ID already exists.
				 */
				duplicateDriverNationalId: () => LocalizedString
			}
		}
	}
	externalPanel: {
		home: {
			/**
			 * External Panel
			 */
			title: () => LocalizedString
			/**
			 * TanStack Router and React Query are configured.
			 */
			description: () => LocalizedString
		}
	}
}

export type Formatters = {}
