// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fa'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		/**
		 * S​w​i​t​c​h​ ​t​o​ ​l​i​g​h​t​ ​m​o​d​e
		 */
		switchToLightMode: string
		/**
		 * S​w​i​t​c​h​ ​t​o​ ​d​a​r​k​ ​m​o​d​e
		 */
		switchToDarkMode: string
		/**
		 * S​w​i​t​c​h​ ​t​o​ ​E​n​g​l​i​s​h
		 */
		switchToEnglish: string
		/**
		 * S​w​i​t​c​h​ ​t​o​ ​P​e​r​s​i​a​n
		 */
		switchToPersian: string
		/**
		 * E​N
		 */
		languageEn: string
		/**
		 * F​A
		 */
		languageFa: string
	}
	validation: {
		/**
		 * U​s​e​r​n​a​m​e​ ​i​s​ ​r​e​q​u​i​r​e​d
		 */
		usernameRequired: string
		/**
		 * U​s​e​r​n​a​m​e​ ​m​u​s​t​ ​b​e​ ​3​–​3​2​ ​c​h​a​r​a​c​t​e​r​s​ ​a​n​d​ ​c​o​n​t​a​i​n​ ​o​n​l​y​ ​l​e​t​t​e​r​s​,​ ​n​u​m​b​e​r​s​,​ ​u​n​d​e​r​s​c​o​r​e​s​,​ ​a​n​d​ ​h​y​p​h​e​n​s
		 */
		usernameInvalid: string
		/**
		 * P​a​s​s​w​o​r​d​ ​i​s​ ​r​e​q​u​i​r​e​d
		 */
		passwordRequired: string
		/**
		 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​{​m​i​n​}​ ​c​h​a​r​a​c​t​e​r​s
		 * @param {number} min
		 */
		passwordMinLength: RequiredParams<'min'>
		/**
		 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​u​p​p​e​r​c​a​s​e​ ​l​e​t​t​e​r
		 */
		passwordUppercase: string
		/**
		 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​l​o​w​e​r​c​a​s​e​ ​l​e​t​t​e​r
		 */
		passwordLowercase: string
		/**
		 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​n​u​m​b​e​r
		 */
		passwordDigit: string
		/**
		 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​o​n​e​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r
		 */
		passwordSpecial: string
	}
	internalPanel: {
		login: {
			/**
			 * I​n​t​e​r​n​a​l​ ​P​a​n​e​l
			 */
			title: string
			/**
			 * A​u​t​h​o​r​i​z​e​d​ ​a​c​c​e​s​s​ ​o​n​l​y
			 */
			subtitle: string
			/**
			 * U​s​e​r​n​a​m​e
			 */
			username: string
			/**
			 * P​a​s​s​w​o​r​d
			 */
			password: string
			/**
			 * y​o​u​r​_​u​s​e​r​n​a​m​e
			 */
			usernamePlaceholder: string
			/**
			 * I​n​v​a​l​i​d​ ​u​s​e​r​n​a​m​e​ ​o​r​ ​p​a​s​s​w​o​r​d​.
			 */
			invalidCredentials: string
			/**
			 * S​i​g​n​i​n​g​ ​i​n
			 */
			signingIn: string
			/**
			 * S​i​g​n​ ​i​n
			 */
			signIn: string
		}
		home: {
			/**
			 * D​a​s​h​b​o​a​r​d
			 */
			title: string
			/**
			 * W​e​l​c​o​m​e​ ​b​a​c​k​,​ ​{​f​i​r​s​t​N​a​m​e​}
			 * @param {string} firstName
			 */
			welcome: RequiredParams<'firstName'>
			/**
			 * S​i​g​n​e​d​ ​i​n​ ​a​s​ ​{​f​i​r​s​t​N​a​m​e​}​ ​{​l​a​s​t​N​a​m​e​}​ ​(​{​u​s​e​r​n​a​m​e​}​)
			 * @param {string} firstName
			 * @param {string} lastName
			 * @param {string} username
			 */
			signedInAs: RequiredParams<'firstName' | 'lastName' | 'username'>
			/**
			 * S​i​g​n​i​n​g​ ​o​u​t​…
			 */
			signingOut: string
			/**
			 * S​i​g​n​ ​o​u​t
			 */
			signOut: string
		}
		nav: {
			/**
			 * D​a​s​h​b​o​a​r​d
			 */
			dashboard: string
			/**
			 * O​p​e​n​ ​m​e​n​u
			 */
			openMenu: string
			/**
			 * S​i​g​n​ ​o​u​t
			 */
			signOut: string
			/**
			 * S​i​g​n​i​n​g​ ​o​u​t​…
			 */
			signingOut: string
			/**
			 * S​i​g​n​ ​o​u​t​?
			 */
			signOutConfirmTitle: string
			/**
			 * Y​o​u​ ​w​i​l​l​ ​n​e​e​d​ ​t​o​ ​s​i​g​n​ ​i​n​ ​a​g​a​i​n​ ​t​o​ ​a​c​c​e​s​s​ ​t​h​e​ ​i​n​t​e​r​n​a​l​ ​p​a​n​e​l​.
			 */
			signOutConfirmDescription: string
			/**
			 * S​i​g​n​ ​o​u​t
			 */
			signOutConfirm: string
			/**
			 * C​a​n​c​e​l
			 */
			cancel: string
		}
		shell: {
			/**
			 * F​u​e​l​ ​C​a​r​r​i​e​r
			 */
			brand: string
			/**
			 * I​n​t​e​r​n​a​l
			 */
			brandSubtitle: string
		}
	}
	externalPanel: {
		home: {
			/**
			 * E​x​t​e​r​n​a​l​ ​P​a​n​e​l
			 */
			title: string
			/**
			 * T​a​n​S​t​a​c​k​ ​R​o​u​t​e​r​ ​a​n​d​ ​R​e​a​c​t​ ​Q​u​e​r​y​ ​a​r​e​ ​c​o​n​f​i​g​u​r​e​d​.
			 */
			description: string
		}
	}
}

export type TranslationFunctions = {
	common: {
		/**
		 * Switch to light mode
		 */
		switchToLightMode: () => LocalizedString
		/**
		 * Switch to dark mode
		 */
		switchToDarkMode: () => LocalizedString
		/**
		 * Switch to English
		 */
		switchToEnglish: () => LocalizedString
		/**
		 * Switch to Persian
		 */
		switchToPersian: () => LocalizedString
		/**
		 * EN
		 */
		languageEn: () => LocalizedString
		/**
		 * FA
		 */
		languageFa: () => LocalizedString
	}
	validation: {
		/**
		 * Username is required
		 */
		usernameRequired: () => LocalizedString
		/**
		 * Username must be 3–32 characters and contain only letters, numbers, underscores, and hyphens
		 */
		usernameInvalid: () => LocalizedString
		/**
		 * Password is required
		 */
		passwordRequired: () => LocalizedString
		/**
		 * Password must be at least {min} characters
		 */
		passwordMinLength: (arg: { min: number }) => LocalizedString
		/**
		 * Password must contain at least one uppercase letter
		 */
		passwordUppercase: () => LocalizedString
		/**
		 * Password must contain at least one lowercase letter
		 */
		passwordLowercase: () => LocalizedString
		/**
		 * Password must contain at least one number
		 */
		passwordDigit: () => LocalizedString
		/**
		 * Password must contain at least one special character
		 */
		passwordSpecial: () => LocalizedString
	}
	internalPanel: {
		login: {
			/**
			 * Internal Panel
			 */
			title: () => LocalizedString
			/**
			 * Authorized access only
			 */
			subtitle: () => LocalizedString
			/**
			 * Username
			 */
			username: () => LocalizedString
			/**
			 * Password
			 */
			password: () => LocalizedString
			/**
			 * your_username
			 */
			usernamePlaceholder: () => LocalizedString
			/**
			 * Invalid username or password.
			 */
			invalidCredentials: () => LocalizedString
			/**
			 * Signing in
			 */
			signingIn: () => LocalizedString
			/**
			 * Sign in
			 */
			signIn: () => LocalizedString
		}
		home: {
			/**
			 * Dashboard
			 */
			title: () => LocalizedString
			/**
			 * Welcome back, {firstName}
			 */
			welcome: (arg: { firstName: string }) => LocalizedString
			/**
			 * Signed in as {firstName} {lastName} ({username})
			 */
			signedInAs: (arg: { firstName: string, lastName: string, username: string }) => LocalizedString
			/**
			 * Signing out…
			 */
			signingOut: () => LocalizedString
			/**
			 * Sign out
			 */
			signOut: () => LocalizedString
		}
		nav: {
			/**
			 * Dashboard
			 */
			dashboard: () => LocalizedString
			/**
			 * Open menu
			 */
			openMenu: () => LocalizedString
			/**
			 * Sign out
			 */
			signOut: () => LocalizedString
			/**
			 * Signing out…
			 */
			signingOut: () => LocalizedString
			/**
			 * Sign out?
			 */
			signOutConfirmTitle: () => LocalizedString
			/**
			 * You will need to sign in again to access the internal panel.
			 */
			signOutConfirmDescription: () => LocalizedString
			/**
			 * Sign out
			 */
			signOutConfirm: () => LocalizedString
			/**
			 * Cancel
			 */
			cancel: () => LocalizedString
		}
		shell: {
			/**
			 * Fuel Carrier
			 */
			brand: () => LocalizedString
			/**
			 * Internal
			 */
			brandSubtitle: () => LocalizedString
		}
	}
	externalPanel: {
		home: {
			/**
			 * External Panel
			 */
			title: () => LocalizedString
			/**
			 * TanStack Router and React Query are configured.
			 */
			description: () => LocalizedString
		}
	}
}

export type Formatters = {}
